In [40]:
from scipy import stats
import numpy as np

In [41]:
# at 94% confidence
np.round(stats.norm.interval(alpha=0.94, loc=200, scale = 30/(2000**0.5)),5)

array([198.73833, 201.26167])

In [43]:
# at 98% confidence
np.round(stats.norm.interval(alpha=0.98, loc=200, scale = 30/(2000**0.5)),5)

array([198.43944, 201.56056])

In [42]:
# at 96% confidence
np.round(stats.norm.interval(alpha=0.96, loc=200, scale = 30/(2000**0.5)),5)

array([198.6223, 201.3777])