In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,confusion_matrix
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
zoo_data = pd.read_csv('Zoo.csv')
zoo_data.head(20)

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0     aardvark     1         0     0     1         0        0         1   
1     antelope     1         0     0     1         0        0         0   
2         bass     0         0     1     0         0        1         1   
3         bear     1         0     0     1         0        0         1   
4         boar     1         0     0     1         0        0         1   
5      buffalo     1         0     0     1         0        0         0   
6         calf     1         0     0     1         0        0         0   
7         carp     0         0     1     0         0        1         0   
8      catfish     0         0     1     0         0        1         1   
9         cavy     1         0     0     1         0        0         0   
10     cheetah     1         0     0     1         0        0         1   
11     chicken     0         1     1     0         1        0         0   
12        chub     0         0     1     0         0        1         1   
13        clam     0         0     1     0         0        0         1   
14        crab     0         0     1     0         0        1         1   
15    crayfish     0         0     1     0         0        1         1   
16        crow     0         1     1     0         1        0         1   
17        deer     1         0     0     1         0        0         0   
18     dogfish     0         0     1     0         0        1         1   
19     dolphin     0         0     0     1         0        1         1   

    toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0         1         1         1         0     0     4     0         0   
1         1         1         1         0     0     4     1         0   
2         1         1         0         0     1     0     1         0   
3         1         1         1         0     0     4     0         0   
4         1         1         1         0     0     4     1         0   
5         1         1         1         0     0     4     1         0   
6         1         1         1         0     0     4     1         1   
7         1         1         0         0     1     0     1         1   
8         1         1         0         0     1     0     1         0   
9         1         1         1         0     0     4     0         1   
10        1         1         1         0     0     4     1         0   
11        0         1         1         0     0     2     1         1   
12        1         1         0         0     1     0     1         0   
13        0         0         0         0     0     0     0         0   
14        0         0         0         0     0     4     0         0   
15        0         0         0         0     0     6     0         0   
16        0         1         1         0     0     2     1         0   
17        1         1         1         0     0     4     1         0   
18        1         1         0         0     1     0     1         0   
19        1         1         1         0     1     0     1         0   

    catsize  type  
0         1     1  
1         1     1  
2         0     4  
3         1     1  
4         1     1  
5         1     1  
6         1     1  
7         0     4  
8         0     4  
9         0     1  
10        1     1  
11        0     2  
12        0     4  
13        0     7  
14        0     7  
15        0     7  
16        0     2  
17        1     1  
18        1     4  
19        1     1

### Data Preperation

In [3]:
zoo_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
 17  type         101 non-null    int64 
dtypes: int64(17), object(1)
memory usage: 14.3+ KB


In [4]:
zoo_data['animal name'].unique()

array(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
       'carp', 'catfish', 'cavy', 'cheetah', 'chicken', 'chub', 'clam',
       'crab', 'crayfish', 'crow', 'deer', 'dogfish', 'dolphin', 'dove',
       'duck', 'elephant', 'flamingo', 'flea', 'frog', 'fruitbat',
       'giraffe', 'girl', 'gnat', 'goat', 'gorilla', 'gull', 'haddock',
       'hamster', 'hare', 'hawk', 'herring', 'honeybee', 'housefly',
       'kiwi', 'ladybird', 'lark', 'leopard', 'lion', 'lobster', 'lynx',
       'mink', 'mole', 'mongoose', 'moth', 'newt', 'octopus', 'opossum',
       'oryx', 'ostrich', 'parakeet', 'penguin', 'pheasant', 'pike',
       'piranha', 'pitviper', 'platypus', 'polecat', 'pony', 'porpoise',
       'puma', 'pussycat', 'raccoon', 'reindeer', 'rhea', 'scorpion',
       'seahorse', 'seal', 'sealion', 'seasnake', 'seawasp', 'skimmer',
       'skua', 'slowworm', 'slug', 'sole', 'sparrow', 'squirrel',
       'starfish', 'stingray', 'swan', 'termite', 'toad', 'tortoise',
       

In [16]:
zoo_data.type.nunique()

7

In [18]:
zoo_data.type.value_counts()

1    41
2    20
4    13
7    10
6     8
3     5
5     4
Name: type, dtype: int64

### model building

In [9]:
X = zoo_data.iloc[:,1:-1]
y = zoo_data.iloc[:,-1:]
X

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     0         0        1  
1           1         1         0     0     4     1         0        1  
2           1         0         0     1     0     1         0        0  
3           1         1         0     0     4     0         0        1  
4           1         1         0     0     4     1         0        1  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96          1         1         0     0     2     1         0        1  
97          0         1         1     0     6     0         0        0  
98          1         1         0     0     4     1         0        1  
99          0         1         0     0     0     0         0        0  
100         1         1         0     0     2     1         0        0  

[101 rows x 16 columns]

In [11]:
std_scale = StandardScaler()
scaled_X = std_scale.fit_transform(X)
scaled_X = pd.DataFrame(data = scaled_X, columns=X.columns)
scaled_X

hair  feathers      eggs      milk  airborne   aquatic  predator  \
0    1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208  0.896421   
1    1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208 -1.115547   
2   -0.861034 -0.496904  0.843721 -0.826640 -0.558291  1.343710  0.896421   
3    1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208  0.896421   
4    1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208  0.896421   
..        ...       ...       ...       ...       ...       ...       ...   
96   1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208 -1.115547   
97   1.161395 -0.496904  0.843721 -0.826640  1.791182 -0.744208 -1.115547   
98   1.161395 -0.496904 -1.185227  1.209717 -0.558291 -0.744208  0.896421   
99  -0.861034 -0.496904  0.843721 -0.826640 -0.558291 -0.744208 -1.115547   
100 -0.861034  2.012461  0.843721 -0.826640  1.791182 -0.744208 -1.115547   

      toothed  backbone  breathes  venomous      fins      legs      tail  \
0    0.809776   0.46569  0.512348 -0.293294 -0.449868  0.572540 -1.698416   
1    0.809776   0.46569  0.512348 -0.293294 -0.449868  0.572540  0.588784   
2    0.809776   0.46569 -1.951800 -0.293294  2.222876 -1.404435  0.588784   
3    0.809776   0.46569  0.512348 -0.293294 -0.449868  0.572540 -1.698416   
4    0.809776   0.46569  0.512348 -0.293294 -0.449868  0.572540  0.588784   
..        ...       ...       ...       ...       ...       ...       ...   
96   0.809776   0.46569  0.512348 -0.293294 -0.449868 -0.415948  0.588784   
97  -1.234909  -2.14735  0.512348  3.409545 -0.449868  1.561027 -1.698416   
98   0.809776   0.46569  0.512348 -0.293294 -0.449868  0.572540  0.588784   
99  -1.234909  -2.14735  0.512348 -0.293294 -0.449868 -1.404435 -1.698416   
100 -1.234909   0.46569  0.512348 -0.293294 -0.449868 -0.415948  0.588784   

     domestic   catsize  
0   -0.384353  1.138180  
1   -0.384353  1.138180  
2   -0.384353 -0.878595  
3   -0.384353  1.138180  
4   -0.384353  1.138180  
..        ...       ...  
96  -0.384353  1.138180  
97  -0.384353 -0.878595  
98  -0.384353  1.138180  
99  -0.384353 -0.878595  
100 -0.384353 -0.878595  

[101 rows x 16 columns]

In [12]:
X_train,X_test,y_train,y_test = train_test_split(scaled_X,y,random_state=12,test_size=0.14,stratify=y, shuffle=True)
X_train.shape,X_test.shape

((86, 16), (15, 16))

### Model training and testing

In [60]:
knn_model = KNeighborsClassifier(n_neighbors=1)
knn_model.fit(X_train,y_train)
y_pred_test = knn_model.predict(X_test)
print("Accuracy   : ",accuracy_score(y_test,y_pred_test))
print("Conf_matrix \n",confusion_matrix(y_test,y_pred_test,))



Accuracy   :  0.9333333333333333
Conf_matrix 
 [[6 0 0 0 0 0 0]
 [0 3 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [51]:
y.type.value_counts()

1    41
2    20
4    13
7    10
6     8
3     5
5     4
Name: type, dtype: int64

In [55]:
grid = GridSearchCV(estimator=knn_model,param_grid={'n_neighbors':range(0,10)})
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(n_neighbors=1),
             param_grid={'n_neighbors': range(0, 10)})

In [56]:
grid.best_params_

{'n_neighbors': 1}